/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "log2(Points + 2)": "log2(点数 + 2)",
    "\"Having a Garden improves your quality of life\"": "“拥有一个花园可以提高你的生活质量”",
    "(Ecological Plant Agency)": "（生态植物局）",
    "(Get 3 Reclaimed Ecosystems)": "(获得 3 个回收的生态系统)",
    "1st Plant!": "第一棵植物！",
    "2 ^ Floor(log10(Points))": "2^地板(log10(点))",
    "Achieve 1,200 Research. Reward: Research Speed x2": "完成1,200项研究奖励：研究速度x2",
    "Achieve a Scientific Breakthrough!": "实现科学突破！",
    "AMERICAN SPACE": "美国太空",
    "Anthurium": "红掌",
    "Attract a Bear to your garden": "将熊吸引到您的花园",
    "Attract a Fox to your Garden": "吸引狐狸到你的花园",
    "Attract your first Animal to the Garden": "将你的第一只动物吸引到花园",
    "Bear-Paw Succulent": "熊掌多肉植物",
    "Begin Generation of Ecology": "生态学的开端",
    "BETTER SPACE": "更好的空间",
    "Bulk buy 50 Plants at once. Reward: Unlock a Garden Milestone": "一次批量购买 50 株植物。奖励：解锁花园里程碑",
    "But": "但",
    "Buy '100% Recycled Materials'": "购买“100% 再生材料”",
    "Buy 'Tipi'": "购买“蒂皮”",
    "Buy a Koi": "买一条锦鲤",
    "Buy a Row 3 Plant Tree Upgrade?": "购买第 3 行植物树升级版？",
    "Buy a Sedum Succulent": "购买景天多肉植物",
    "Buy a Snake Plant": "买一株蛇植物",
    "Buy a Time Speed Increase": "购买时间速度提升",
    "Buy an Anthurium": "买一朵红掌",
    "Buy Plant Robotics": "购买植物机器人",
    "Buy your first Plant": "购买你的第一株植物",
    "Cleaning - Fish Edition": "清洁-鱼版",
    "Coconut Palm": "椰子树",
    "Combined": "组合",
    "Complete 'Abandoned Quarry' Twice": "完成“废弃采石场”两次",
    "Complete 'Polluted Ocean' Twice": "完成两次“污染的海洋”",
    "Complete the Reference": "完成参考",
    "Costco sells plants now!": "Costco 现在有卖植物啦！",
    "Daft Wildlife": "愚蠢的野生动物",
    "Didn't know there was that much space": "不知道有这么大的空间",
    "Ecosystem Lost": "生态系统消失",
    "EPA": "美国环保局",
    "Finally, Some Satisfaction!": "最后，有点满意！",
    "Find 50 Fish": "找到 50 条鱼",
    "Floor(plants ÷ 10) x 10": "地板（植物/10）x 10",
    "Fully Complete the Tropical Zone": "完全完成热带地区",
    "Gain a Second Ecosystem. Reward: Divide Ecosystem Requirements by 1.20": "获得第二个生态系统奖励：将生态系统要求除以1.20",
    "Get 'Americas Inspired Zone'": "获得“美洲风情区”",
    "Get 300 Leaves": "获得 300 片树叶",
    "Get 370 Plants in The Alpine Zone. Reward: 2x Point gain under 3 Zones": "在高山地区获得 370 株植物。奖励：3 个区域下获得 2 倍点数",
    "Get a Garden Milestone. Reward: Prickly Pears don't use up Plants": "获得花园里程碑。奖励：刺梨不会耗尽植物",
    "Get a new Garden": "获得一个新花园",
    "Get a new Zone": "获取新区域",
    "Get an Overpowered Boost from a Certain Research Upgrade": "从某些研究升级中获得超强的提升",
    "Get Ecosystem Milestone 2": "获取生态系统里程碑 2",
    "Habitat Master": "栖息地大师",
    "Hard Work!": "辛苦了！",
    "Have 100 Plants": "拥有 100 株植物",
    "Have Infinite (1.8e308) Wildlife per Plant": "每株植物拥有无限 (1.8e308) 野生动物",
    "Jade Plant": "玉树",
    "Just 1 More Completion...": "只剩下 1 个完成...",
    "Magnitude of x: log10(x)": "x 的量级：log10(x)",
    "Make Prickly Pears cheaper than 0.01 Plants": "使刺梨比 0.01 植物便宜",
    "Make Prickly Pears Cheaper Than 1.80e-308 Plants, Don't worry, this will be out of order": "使刺梨比 1.80e-308 植物便宜，别担心，这会出问题",
    "Make Prickly Pears cheaper than 3 Plants. Reward: Keep plant upgrades on Garden reset": "使刺梨比 3 种植物便宜。奖励：在花园重置时保留植物升级",
    "More Resources?": "更多资源？",
    "MORE SPACE": "更多的空间",
    "Multiply point gain based on points": "基于点的乘点增益",
    "Multiply Point gain by plants. Currently: x1.00": "乘以植物的点数增益。",
    "Obtain All the Habitats": "获得所有栖息地",
    "Philodendron": "喜林芋",
    "PLACES WHICH HELP YOU GET BETTER SPACE": "帮助您获得更好空间的地方",
    "Plant Central": "植物中心",
    "Plant costs are divided based on magnitude": "植物成本根据量级除以",
    "Plant costs are divided by plants": "植物成本按植物除以",
    "Plant costs are divided by points": "植物成本除以点数",
    "Plant costs divided by plants, only goes up at intervals of 10": "植物成本除以植物，仅以 10 为间隔增加",
    "Plant Points": "植物点数",
    "plants": "植物",
    "Play The Plant Tree Inside of The Plant Tree": "玩植物树里面的植物树",
    "Points ^ 0.1": "点数^0.1",
    "Points are multiplied based on magnitude": "点数基于量级相乘",
    "Press CTRL to See Specific Values": "按 CTRL 键查看具体值",
    "Prickly Pears from": "刺梨来自",
    "Prickly Pears from IKEA": "宜家的刺梨",
    "Prickly Pears from the Desert": "来自沙漠的刺梨",
    "Quality OF LIFE": "生活质量",
    "Reach 100 Wildlife": "野生动物数量达到 100 种",
    "Reach the Echinocactus Limit. Reward: Keep Plant Buyables on Garden Reset": "达到仙人球限制。奖励：在花园重置时保留植物可购买物品",
    "Real Wildlife!": "真正的野生动物！",
    "Reclaim 3 Ecosystems": "回收 3 个生态系统",
    "Recursion": "递归",
    "Recycle 50 Times": "循环使用50次",
    "Research for Infinitely (1.8e308) Long": "无限长 (1.8e308) 的研究",
    "RETURN OF THE MAGNITUDE": "量级回归",
    "Sassy Wildlife": "时髦的野生动物",
    "Sedum": "景天属",
    "Set devSpeed to": "将 devSpeed 设置为",
    "Snake Plant": "虎尾兰",
    "Square milestone effect": "方形里程碑效应",
    "Sub-Milestones?": "子里程碑？",
    "TAINABLE SPACE": "可用空间",
    "The Fishing Trip": "钓鱼之旅",
    "The Knockoff Trees": "仿冒树",
    "The Plant Tree Discussion": "植物树讨论",
    "The Plants...": "植物...",
    "The Reclaimer": "回收者",
    "the Void": "虚空",
    "This Isn't How The Food Chain Works...": "这不是食物链的运作方式......",
    "this you Speak of?": "你说的是这个吗？",
    "Time Control": "时间控制",
    "Time Portal": "时间传送门",
    "Time Walrus": "时间海象",
    "Uh oh, this achievement name contains spoilers!": "呃哦，这个成就名称有剧透！",
    "Unlock Gardens and double point gain": "解锁花园并获得双倍点数",
    "Unlock More Wildlife Upgrades": "解锁更多野生动物升级",
    "What does divided mean?": "分开是什么意思？",
    "What does Magnitude mean?": "量级是什么意思？",
    "What Does This Mean?": "这是什么意思？",
    "What is": "这是",
    "Wildlife Central": "野生动物中心",
    "You Can Stop Now": "你现在可以停下来",
    "You need more containers": "您需要更多容器",
    "You Need More Trash Cans": "你需要更多垃圾桶",
    "Yucca": "丝兰",
    "Achievement Gotten!": "成就达成！",
    "Prickly Pear": "刺梨",
    "Saguaro": "仙人掌",
    "Total Effect:": "总效果：",
    "Divide plant costs by 10. Hold to buy max.": "将植物成本除以 10。按住以购买最大。",
    "Multiply point gain and divide plant costs by 5. Hold to buy max.": "乘以点数增益并将植物成本除以 5。按住以购买最大。",
    "(Gardens + 1) x (Plants + 1)": "（花园 + 1）x（植物 + 1）",
    "Ceramic Pots": "陶瓷盆",
    "Divide buyable cost based on magnitude of plants": "根据植物量级除以可购买成本",
    "Divide Garden costs based on Magnitude of Plants": "根据植物的量级除以花园成本",
    "Garden upgrade 1-1 also divides plant costs": "花园升级1-1也分摊了植物成本",
    "gardens": "花园",
    "Lawn": "草地",
    "Multiply point gain based on Gardens and Plants": "基于花园和植物的多点增益",
    "Plants don't reset anything, automatically reset for plants and unlock a new row of Plant upgrades": "植物不会重置任何东西，自动重置植物并解锁新的一行植物升级",
    "Raised Beds": "高架床",
    "Raised Beds II": "高架床 II",
    "Shed": "棚屋",
    "Terracotta Pots": "赤土陶罐",
    "Unlock a Plant buyable": "解锁可购买的植物",
    "Unlock another buyable": "解锁另一个可购买",
    "Divide plant costs by gardens": "将植物成本除以花园",
    "Woodshed": "木棚",
    "Chives": "韭菜",
    "Decking I": "铺板 I",
    "Decking II": "铺板 II",
    "Decking III": "铺板 III",
    "Decking IV": "铺板 IV",
    "Divide Garden costs based on points": "根据点数除以花园成本",
    "Garden Upgrade 1-1 Uses Zones as well": "花园升级 1-1 也使用区域",
    "Garden upgrade 1-4's effect is better": "花园升级1-4的效果更好",
    "Greenhouse": "温室",
    "Mint": "薄荷",
    "Parsley": "香菜",
    "Plants multiply point gain slightly": "植物略微增加点增益",
    "Previous Plant upgrades based on magnitude are better": "以前基于量级的植物升级效果更好",
    "Reduce \"Prickly Pear\" base by 0.1": "将“刺梨”基础减少 0.1",
    "Rosemary": "迷迭香",
    "Unlock Zones": "解锁区域",
    "Garden Upgrade 2-2 is better": "花园升级 2-2 更好",
    "Date Palm": "枣椰树",
    "Divide Plant costs based on Points and Plants": "根据点数和植物除以植物成本",
    "Divide point gain by Plants": "按植物除以点数增益",
    "Reward:": "奖励：",
    "The Tropical Zone": "热带地区",
    "Unlock 1: The Tropical Zone": "解锁1：热带地区",
    "Unlock 2: The Alpine Zone": "解锁2：高山地区",
    "Unlock 3: The Temperate Zone": "解锁3：温带地区",
    "Unlock 4: The Forest Zone": "解锁4：森林地区",
    "Unlock new Content": "解锁新内容",
    "zones": "区域",
    "Multiply point gain based on Gardens": "乘以点数增益基于花园",
    "Divide Garden costs based on Points": "除以花园成本基于点数",
    "Half Whisky Barrel": "半威士忌桶",
    "Acai Palm": "巴西莓棕榈",
    "Areca Palm": "槟榔",
    "Divide \"Prickly Pear\" cost based on Plants and divide \"Saguaro\" costs by it's amount": "根据植物除以“仙人掌”成本，并将“仙人掌”成本除以其数量",
    "Multiply Point gain based on Tropical Zone completions and Zones": "基于热带地区完成情况和区域的乘数增益",
    "Plant cost formula: Base (2->1.9) ^ Plants ^ Exponent (1)": "植物成本公式：基数 (2->1.9) ^ 植物 ^ 指数 (1)",
    "Sago Palm": "西米棕榈",
    "((Completions + 1) x (Zones + 1)) ^ 2": "((完成 + 1) x (区域 + 1)) ^ 2",
    "(Gardens ÷ 2) + 1": "(花园 ÷ 2) + 1",
    "The Alpine Zone": "高山地区",
    "Previous Challenge Effects and Gain is divided by and plant costs are multiplied by Prickly Pear purchases": "以前的挑战效果和收益除以植物成本乘以刺梨购买量",
    "Cost increases when Plant Upgrade 5-1 is bought. Formula: log2(Points)": "当购买植物升级 5-1 时成本增加，公式：log2(点数)",
    "Cost increases when Plant Upgrade 5-2 is bought. Formula: 2 ^ (Plants ^ 0.5)": "购买植物升级 5-2 时成本会增加。公式：2 ^ (植物 ^ 0.5)",
    "Multiply Point gain based on Plants": "乘以点数增益基于植物",
    "Sempervivum": "长生花",
    "Stonecrop": "景天",
    "Prickly Pear cost is divided based on points": "刺梨成本降低基于点数",
    "Campanula": "风铃",
    "Cost increases when Plant Upgrade 5-3 is bought": "购买植物升级 5-3 后成本会增加",
    "Cost increases when Plant Upgrade 5-4 is bought": "购买植物升级 5-4 时成本会增加",
    "Phlox": "福禄考",
    "Prickly Pear multiplies Point gain by 10 instead": "刺梨将点数增益乘以 10",
    "Saguaro multiplies Point gain by 2": "仙人掌将点数增益乘以 2",
    "Cost increases when Plant Upgrade 6-1 is bought": "购买植物升级 6-1 后成本会增加",
    "Cost increases when Plant Upgrade 6-2 is bought": "购买植物升级 6-2 后成本会增加",
    "Dianthus": "石竹",
    "Echinocactus is 'free' and gives bonus levels to Saguaro and Prickly Pear": "仙人球 是“免费”的，并为 仙人掌 和 刺梨 提供奖励等级",
    "Prickly Pear gives bonus levels to Saguaro": "刺梨为仙人掌提供奖励等级",
    "Primrose": "报春花",
    "Pulsatilla Vulgaris": "白头翁",
    "Saguaro amount divides Prickly Pear cost": "仙人掌数量除以刺梨成本",
    "Thrift": "海石竹",
    "Unlock a buyable": "解锁可购买",
    "Half Barrel Pond": "半桶形水池",
    "Echinocactus": "仙人球",
    "Multiply Plant cost base above 1 by 0.99. Hold to buy max.": "将高于 1 的植物成本基数乘以 0.99。按住最多可购买。",
    "Previous Challenge Effects and Point Gain is divided by log10 Points": "之前的挑战效果和点数增益除以 log10 点数",
    "The Temperate Zone": "温带地区",
    "Multiply Point Gain by Temperate Zone Completions. (free) Hold to buy max.": "将点数增益乘以温带完成次数。（免费）按住最多可购买。",
    "Multiply Point Gain by Zones. (free) Hold to buy max.": "将点数增益乘以区域。（免费）按住可购买最多。",
    "Temp. Zone Completions + 1 ^ X. Currently Multiplying Point Gain when bought by x3.00": "临时区域完成 + 1 ^ X. 当前购买时的点数增益乘以 x3.00",
    "Tunnel Features": "隧道功能",
    "Water Features": "水源功能",
    "Zones + 1 ^ X. Currently Multiplying Point Gain when bought by x4.00": "区域 + 1 ^ X。当前购买时点数增益乘以 x4.00",
    "Access to Pond for Wildlife": "进入野生动物池塘",
    "Reduce Row 1 Garden Buyable Scaling by 3": "将第 1 行花园可购买比例减少 3",
    "Exploration Features": "探索功能",
    "Multiply Point Gain based on total first row Garden Buyable Purchases. (free) Hold to buy max.": "根据第一排花园可购买购买总数乘以点数增益。（免费）按下以购买最大。",
    "5th Root(log5(Gardens))": "五次根(log5(花园))",
    "Divide Garden Costs based on Gardens": "根据花园除以花园成本",
    "Gardens Divide Zone Requirements": "花园除以区域要求",
    "Hot Tub": "热水浴缸",
    "Previous Challenge Effects and Saguaro is Unavailable": "之前的挑战效果和仙人掌不可用",
    "The Forest Zone": "森林地带",
    "Wild Garlic": "野蒜",
    "log5 (log5 (Points))": "log5 (log5 (点数))",
    "sqrt (Research ÷ 100) ÷ 5 + 1": "sqrt (研究 ÷ 100) ÷ 5 + 1",
    "sqrt (log2 (Fish))": "sqrt (log2 (鱼))",
    "Actually Buy Max Prickly Pears": "实际上购买 最大刺梨",
    "Advanced Requirement Reduction": "高级需求减少",
    "Air-Diluted Water": "空气稀释水",
    "Also known as 'Bubbles', same as 'Plant Robotics'": "也称为“气泡”，与“植物机器人”相同",
    "Autobuy Prickly Pear, Increase 'Nutrients' limit by 5 and Research Time is Multiplied Based on it's Magnitude": "自动购买刺梨，将“营养素”限制增加5，研究时间根据其大小成倍增加",
    "Better": "更好的",
    "Divide Plant Costs Based on Researchers. Hold to Buy Max.": "根据研究人员划分植物成本。持有以购买 Max。",
    "Divide Research Requirement Based on Plants. (free) Hold to buy max.": "根据植物划分研究需求（免费）持有最多可购买。",
    "Divide Research Requirement by 2,115. Hold to buy max.": "将研究要求除以 2,115。持有最多可购买。",
    "Divide Research Requirement by Research. Hold to buy max.": "将研究需求除以研究。持有最多可购买。",
    "Fishing Pole": "钓鱼竿",
    "Garden Costs are Divided by This Buyable's Amount. Hold to Buy Max.": "花园成本除以该可购买的金额。持有至购买上限。",
    "Genetic Modification": "基因改造",
    "Hold to buy max.": "持有以购买最大。",
    "Increase Nutrients Limit by 5": "将营养素限制增加 5",
    "Increase Requirement Reduction and Wildlife Booster Base by 1. Hold to buy max.": "将需求减少和野生动物助推器基础增加 1。持有以购买最多。",
    "Increase Time Speed Increase Base by 2. Hold to buy max.": "增加时间速度将基础增加 2。持有可购买最大。",
    "Larger Wildlife Gain is Multiplied by Research. Hold to Buy Max.": "更大的野生动物收益乘以研究。持有以购买最大。",
    "Light Strengthener": "光增强剂",
    "Light-Leaf Penetration": "光叶穿透",
    "Linear": "线性",
    "Logarithmic": "对数",
    "Lure": "饵",
    "Much": "很多",
    "Multiply Ecology Gain Based on Fish": "以鱼类为基础倍增生态增益",
    "Multiply Fish Gain Based on Research": "根据研究增加鱼的增益",
    "Multiply Leaf Gain based on Their own Magnitude": "根据树叶自身的大小乘以树叶增益",
    "Multiply Research Time by Wildlife Boosters, Autobuy Nutrients and Increase its Limit by 5": "将研究时间乘以野生动物助推器、自动购买营养物质并将其限制增加 5",
    "Plant Division": "植物事业部",
    "Plant Robotics": "植物机器人",
    "Plant Robotics Mk II": "植物机器人 Mk II",
    "Plants -> Wildlife Conversion is Better": "植物 -> 野生动物转换更好",
    "Plants Boost Research Time Gain": "植物增加研究时间",
    "Point Research Facility": "点研究设施",
    "Points Boost Research Time Gain": "点数可增加研究时间",
    "Reduce 'Advanced Requirement Reduction' Cost scaling to 9": "将“高级需求减少”成本缩放减少至 9",
    "Refining Research": "炼油研究",
    "Requirement Reduction": "需求减少",
    "Requirement Reduction II": "降低要求 II",
    "Research": "研究",
    "Research Booster": "研究助推器",
    "Research Effect is": "研究效果为",
    "Research Superbooster": "研究超级助推器",
    "Researcher Based Buyables' Cost Scaling is Reduced by 1": "基于研究人员的可购买产品的成本比例降低了 1",
    "Researchers": "研究人员",
    "Reset Researchers but Multiply Their Gain based on Research Time. Hold to Buy Max.": "重置研究人员，但根据研究时间乘以他们的收益。持有以购买最大。",
    "Resource Abundance": "资源丰富",
    "Scientific Breakthrough": "科学突破",
    "Smarter Wildlife": "更聪明的野生动物",
    "Time Speed Increase": "时间速度增加",
    "Time Speed Superincrease": "时间速度超增",
    "Trees are Part of the Plant Layer": "树木是植物层的一部分",
    "Unlock 4 New Wildlife Upgrades": "解锁 4 种新的野生动物升级",
    "Unlock Trees": "解锁树木",
    "Unlocks more Wildlife Upgrades after 2 Purchases.": "购买 2 次后可解锁更多野生动物升级。",
    "Upcycling": "升级再造",
    "Uses '1.6 ^' Instead of '2 ^' Plant Robotics Magnitude is Separate and unaffected by 'Parsley'": "使用“1.6 ^”而不是“2 ^”植物机器人量级是独立的并且不受“欧芹”的影响",
    "Wait... holup... holy frick is that an achievement outside of the achievements layer!? bro": "等等...holup...天哪，这是成就层之外的成就吗！？兄弟",
    "Wildlife Booster": "野生动物助推器",
    "Wildlife Conversion Booster": "野生动物转化助推器",
    "Wildlife Superbooster": "野生动物超级助推器",
    "Wildlife-Friendly Fertilizer": "对野生动物友好的肥料",
    "10rt (Leaves)": "10rt (树叶)",
    "(Trees ÷ 100) ^ 0.2": "(树 ÷ 100) ^ 0.2",
    "log5 (Wildlife)": "log5 (野生动物)",
    "'^ 500' Instead of '^ 100'": "'^ 500' 而不是 '^ 100'",
    "A Increase": "增加",
    "A is Increased Based on Leaves": "A 在树叶的基础上增加",
    "A is Increased by Trees": "A 因树而增加",
    "Adverse-Vaxxers": "逆向疫苗接种者",
    "and Plant Costs": "和植物成本",
    "Anti-Vaxxers": "反疫苗者",
    "Apple Tree": "苹果树",
    "Apricot Tree": "杏树",
    "Automatically Buy the First 4 Garden Buyables": "自动购买前 4 个花园可购买物品",
    "Automatically Reset for Gardens, Automatically buy Research Buyables and Reduce Research Base by 0.05": "自动重置花园、自动购买研究可购买物品并将研究基地减少 0.05",
    "B Increase": "B 增加",
    "B is Increased Based on Leaves": "B是在树叶的基础上增加的",
    "C Increase": "C 增加",
    "C is Increased Based on Leaves": "C是根据树叶增加的",
    "Divide Garden Costs based on Trees": "根据树木划分花园成本",
    "Divide Plant Costs by Leaves Effect at an Increased Rate": "以更高的比率将植物成本除以树叶效应",
    "Ecosystems": "生态系统",
    "Every Tree Generates 1 Leaf Every Second": "每棵树每秒生成一片树叶",
    "Gardens": "花园",
    "Increase A by 1. Hold to Buy Max.": "将 A 增加 1。持有至买入最大值。",
    "Increase B by 1. Hold to Buy Max.": "将 B 增加 1。持有至买入最大值。",
    "Increase C by 1. Hold to Buy Max.": "将 C 增加 1。持有至买入最大值。",
    "Increase the Tree of Life Buyables Limit by 5": "将生命之树可购买上限提高 5 个",
    "Incremental God Tree": "增量神树",
    "Keep Points on Research Reset": "保留研究重置点",
    "Leaf Effect: (Leaves ÷ 100) ^ 100": "树叶效果：（树叶 ÷ 100）^ 100",
    "Multiply Leaf Gain Based on Zones": "根据区域乘以树叶增益",
    "Multiply Leaf Gain by Research": "通过研究使叶片增益倍增",
    "Multiply Point Gain based on A, B and C and Unlock Buyables for Each": "基于 A、B 和 C 乘以点数增益并解锁每个的可购买物品",
    "Multiply Research Speed based on Leaves": "基于树叶倍增研究速度",
    "Multiply Research Speed Based on Trees": "基于树倍增研究速度",
    "Multiply Research Speed by Trees": "研究速度乘以树木",
    "Pear Tree": "梨树",
    "Plants": "植物",
    "sqrt (Leaves)": "sqrt（树叶）",
    "The Camellia Tree Rewritten": "重写的山茶花树",
    "The Milestone Tree": "里程碑树",
    "The Plague Tree": "瘟疫树",
    "The Plant Tree": "植物树",
    "Tree Effect is now ^ 100 and Doesn't Affect Plant Costs and Research Buyables Cost Nothing": "树木效应现在为 ^ 100，不会影响植物成本，并且研究可购买物品无需任何成本",
    "Tree of Life": "生命之树",
    "trees": "树",
    "Trees": "树",
    "Trees are Multiplying Point gain": "树正在乘以点增益",
    "Unlock a Miniature Version of": "解锁迷你版",
    "Unlock a New Row of Research Upgrades": "解锁一系列新的研究升级",
    "Unlock Ecosystems": "解锁生态系统",
    "Unlock Tree Milestones": "解锁树里程碑",
    "Unlocks Standard Notation": "解锁标准符号",
    "Wildlife": "野生动物",
    "Wildlife Multiplies Research Speed": "野生动物使研究速度倍增",
    "You Can Increase Tree Bulk to 10": "您可以将树体积增加到 10",
    "You Keep Leaves on Tree Reset and Multiply Their Gain based on Themselves": "您将树叶保留在树上重置并根据自身乘以它们的增益",
    "Zones": "区域",
    "Zones ^ 3": "区域^3",
    "'Nutrients' Divides Prickly Pear Cost at a Reduced Rate": "“营养素”以较低的比例分摊仙人掌成本",
    "2rt(Plants) -> 1.5rt(Plants)": "2rt（植物） -> 1.5rt（植物）",
    "3rt (Zones)": "第三区（区域）",
    "Ability Cooldown Divided based on Zones": "技能冷却时间按区域划分",
    "Base Wildlife Gain uses a Better Formula": "基础野生动物增益使用更好的公式",
    "Bluebells": "风信子",
    "Cabbage": "卷心菜",
    "Cauliflower": "菜花",
    "Filmy Fern": "薄膜蕨类植物",
    "First Ecosystem Ability Effect also Divides Garden Costs at a Reduced Ra": "第一个生态系统能力效应也以降低的 Ra 分摊花园成本",
    "log10 (Effect) ^ 0.1": "log10（效果）^ 0.1",
    "Nutrients ^ 0.1": "营养素^0.1",
    "Reduce Echinocactus Scaling by 10": "将金龟子鳞片减少 10",
    "Tree Fern": "树蕨",
    "First Ecosystem Ability Effect also Divides Garden Costs at a Reduced Rate": "第一个生态系统能力效应也以较低的比例分摊花园成本",
    "African Inspired Zone": "非洲风情区",
    "Americas Inspired Zone": "美洲风情区",
    "Asian Inspired Zone": "亚洲风情区",
    "Autobuy Echinocactus and Reduce its Cost": "自动购买金龟子并降低其成本",
    "Autobuy Tree of Life Buyables": "自动购买生命之树可购买物品",
    "Automatically Reset for Zones": "自动重置区域",
    "Coming Soon...": "即将推出...",
    "European Inspired Zone": "欧洲风情区",
    "Generate 1% of Pending Fish Gain Every Second": "每秒产生 1% 的待鱼增益",
    "Keep Zone Upgrades on Reset": "保持区域升级处于重置状态",
    "log30 (Zones)": "log30（区域）",
    "Multiply Echinocactus Limit by 2 but Superscaling Starts": "将金盏花限制乘以 2，但超级缩放开始",
    "Multiply Ecology Gain and 'Recycling' Cost by Zones": "按区域乘以生态收益和“回收”成本",
    "Multiply Ecology Gain by Zones": "按区域乘以生态增益",
    "Raise Research Time to a Power Based on Zones": "将研究时间提高到基于区域的幂",
    "Reduce the Plant Exponent by 0.01": "将植物指数减少 0.01",
    "Unlock 4 Zone Upgrades Which Reset Plants on Purchase": "解锁 4 个区域升级，可在购买时重置植物",
    "log10 (Fish)": "log10 (鱼)",
    "log10 (Wildlife)": "log10 (野生动物)",
    "Olm": "洞螈",
    "Owl": "猫头鹰",
    "2rt (log2 (Mult))": "2rt (log2 (乘数))",
    ". Cost increases when 'Meadow' is Bought": ".购买“草地”时成本增加",
    "'Exploration Features' Amount": "“探索特征”数量",
    "'Nutrients' affects Wildlife Gain at a Reduced Rate": "“营养素”对野生动物增益的影响降低",
    "(log10 (Wildlife × LW)) ^ 0.1. Requires 'Cave' and 'Faster Wildlife' (R:ab:bit)": "(log10 (野生动物 × LW)) ^ 0.1。需要“洞穴”和“更快的野生动物”(R:ab:bit)",
    "(sqrt (Reset Time))rt (100)": "(sqrt（复位时间））rt (100)",
    "^ 0.1 -> ^ 0.5. Requires 'Meadow' and 'Faster Wildlife'": "^ 0.1 -> ^ 0.5。需要“草地”和“更快的野生动物”",
    "0.3. Requires 'Pond' and 'Faster Wildlife'": "0.3. 需要“池塘”和“更快的野生动物”",
    "3rt (log3 (Points)). Requires 'Meadow' and 'Bigger Wildlife'": "3rt（log3（点））。需要“草地”和“更大的野生动物”",
    "50rt (log50 (Fish))": "50rt (log50 (鱼))",
    "after wildlife loss": "野生动物消失后",
    "Alligator": "鳄鱼",
    "Anteater": "食蚁兽",
    "Autobuy Saguaro and Divide its cost by Wildlife x Plants x its Amount": "自动购买 Saguaro 并将其成本除以野生动物 x 植物 x 其数量",
    "Badger": "獾",
    "Bat": "蝙蝠",
    "Bear": "熊",
    "Bigger Wildlife": "更大的野生动物",
    "Bream": "鳊鱼",
    "Cave": "洞穴",
    "Centipede": "蜈蚣",
    "Common Carp": "鲤鱼",
    "Cost Increases when Stronger Wildlife is Bought": "购买更强大的野生动物时成本会增加",
    "Divide Garden Costs based on Wildlife (Boosted by Large Wildlife)": "根据野生动物划分花园成本（大型野生动物推动）",
    "Divide Plant Costs Based on Fish": "根据鱼类划分工厂成本",
    "Divide Saguaro cost based on points. Only Reduces Large Wildlife by 10% of Cost. Hold to buy max.": "根据点数划分仙人掌成本。仅减少大型野生动物成本的 10%。持有可购买最大数量。",
    "Divide Zone Requirements Based on Research Requirement Multiplier": "根据研究需求乘数划分区域需求",
    "Double 'Recycling' Limit but Superscaling Starts": "双倍“回收”限制但超级规模开始",
    "Dragonfly": "蜻蜓",
    "Eel": "鳗鱼",
    "Effect ^ 0.1. Requires 'Pond' and 'Smarter Wildlife'": "效果 ^ 0.1。需要“池塘”和“更聪明的野生动物”",
    "Every Upgrade in this Row Doubles Research Speed": "此行中的每次升级都会使研究速度加倍",
    "Faster Wildlife": "更快的野生动物",
    "Field Mouse": "田鼠",
    "Find Fish": "寻找鱼",
    "Fire Ant": "火蚁",
    "Fish": "鱼",
    "Fish Multiply Their own Gain": "鱼乘以自身收益",
    "Fish Nerf Plant Cost Exponent": "鱼 Nerf 工厂成本指数",
    "floor (log2 (Fish))": "floor（log2（鱼））",
    "Fox": "狐狸",
    "Gudgeon": "虾虎鱼",
    "Hedgehog": "刺猬",
    "Increase Passive Fish Generation (20 Zones) by 1% per Ecosystem": "每个生态系统被动鱼的生成量（20 个区域）增加 1%",
    "Kestrel": "红隼",
    "Koi": "锦鲤",
    "Largemouth Bass": "大口黑鲈",
    "Larger Wildlife -> Wildlife effect is Better": "野生动物更大->野生动物效果更好",
    "Larger Wildlife 'Point Mult' also Divides Plant Costs": "更大的野生动物“点多”也分摊了植物成本",
    "Larger Wildlife Effect also Multiplies Research Time Gain": "更大的野生动物影响也成倍增加研究时间",
    "Log Pile": "原木堆",
    "log2 (Effect ^ 0.5). Requires 'Pond' and 'Stronger Wildlife'": "log2（效果 ^ 0.5）。需要“池塘”和“更强的野生动物”",
    "log20 (Points ^ 0.05) x lo4(Wildlife ^ 0.25). Requires 'Log Pile' and 'Longer Wildlife'": "log20（点数 ^ 0.05）x lo4（野生动物 ^ 0.25）。需要“原木堆”和“更长的野生动物”",
    "Longer Wildlife": "更长的野生动物",
    "Main": "主界面",
    "Meadow": "草地",
    "Meerkat": "猫鼬",
    "Multiply Leaf Gain by 100, Effect Decays over Ecosystem Reset": "将叶子增益乘以 100，效果会因生态系统重置而衰减",
    "Multiply Point and Wildlife Gain based on Points and Wildlife": "根据点数和野生动物乘以点数和野生动物增益",
    "Multiply Point Gain based on Plants": "基于植物的乘点增益",
    "Multiply Point gain based on Wildlife": "基于野生动物的乘数增益",
    "Multiply Research Speed by Zones": "按区域倍增研究速度",
    "Multiply Research Time Based on Fish": "根据鱼类乘以研究时间",
    "Multiply Wildlife Gain Based on Fish": "基于鱼类增加野生动物增益",
    "Multiply Wildlife Gain based on Magnitude": "根据强度乘以野生动物增益",
    "Multiply Wildlife gain Based on Points": "根据点数乘以野生动物增益",
    "Multiply Wildlife gain based on Zones": "根据区域乘以野生动物增益",
    "Newt": "蝾螈",
    "Nutrients": "营养素",
    "Pike": "梭子鱼",
    "Plant costs are Divided by Wildlife": "植物成本除以野生动物",
    "Plants Boost Wildlife Gain": "植物促进野生动物增益",
    "Point Gain is Multiplied Based on Fish": "点数增益根据鱼而倍增",
    "Point gain mult: LW ^ 0.5. Wildlife gain mult: LW ^ 0.1. Requires 'Cave' and 'Bigger Wildlife'": "点数增益乘数：LW ^ 0.5。野生动物增益乘数：LW ^ 0.1。需要“洞穴”和“更大的野生动物”",
    "Points ^ N where N is X ÷ 100. Currently: ÷e1.148e9": "点 ^ N，其中 N 为 X ÷ 100。当前：÷e1.148e9",
    "Pond": "池塘",
    "Pond Skater": "池塘溜冰者",
    "Rabbit": "兔子",
    "Raccoon": "浣熊",
    "Rainbow Trout": "虹鳟鱼",
    "Reduce Garden Buyable Cost scaling by 2": "将花园可购买成本降低 2 倍",
    "Replace ^ 0.1 of Wildlife with Larger Wildlife every second which helps Multiply Point gain and Wildlife Gain": "每秒将 ^ 0.1 的野生动物替换为更大的野生动物，这有助于乘以点数增益和野生动物增益",
    "Requires 'Cave' and 'Smarter Wildlife'": "需要“洞穴”和“更聪明的野生动物”",
    "Requires 'Cave' and 'Stronger Wildlife'": "需要“洞穴”和“更强的野生动物”",
    "Requires 'Log Pile' and 'Bigger Wildlife'": "需要“原木堆”和“更大的野生动物”",
    "Requires 'Log Pile' and 'Faster Wildlife'": "需要“原木堆”和“更快的野生动物”",
    "Requires 'Log Pile' and 'Smarter Wildlife'": "需要“原木堆”和“更聪明的野生动物”",
    "Requires 'Log Pile' and 'Stronger Wildlife'": "需要“原木堆”和“更强的野生动物”",
    "Requires 'Log Pile' and 'Wildlife Booster' x2": "需要“原木堆”和“野生动物助推器”x2",
    "Requires 'Meadow' and 'Smarter Wildlife'": "需要“草地”和“更聪明的野生动物”",
    "Requires 'Meadow' and 'Stronger Wildlife'": "需要“草地”和“更强大的野生动物”",
    "Requires 'Meadow' and 'Wildlife Booster' x2": "需要“草地”和“野生动物助推器”x2",
    "Requires 'Pond' and 'Longer Wildlife'": "需要“池塘”和“更长的野生动物”",
    "Research Effect Multiplies Wildlife Gain at a Reduced Rate": "研究效果以降低的速度使野生动物增益倍增",
    "Research Time Boosts itself": "研究时间自我提升",
    "Research Time Multiplies Wildlife Gain": "研究时间使野生动物数量成倍增加",
    "Reset Ecology and Wildlife to Gain": "重置生态和野生动物以获得收益",
    "Roach": "拟鲤",
    "Roe Deer": "狍子",
    "Rudd": "赤睛鱼",
    "Saguaro Multiplies Wildlife Gain at a Reduced Rate": "仙人掌以较低的速度增加野生动物的增益",
    "Spider": "蜘蛛",
    "sqrt (log2 (Effect)). Requires 'Meadow' and 'Longer Wildlife'": "sqrt (log2 (效果))。需要“草地”和“更长的野生动物”",
    "sqrt(Gardens)": "sqrt（花园）",
    "sqrt(Zones). Requires 'Pond' and 'Bigger Wildlife'": "sqrt(地区)). 需要“池塘”和“更大的野生动物”",
    "Stickleback": "刺鱼",
    "Stronger Wildlife": "更强的野生动物",
    "Swan": "天鹅",
    "Tench": "丁鱥",
    "Time ^ 0.2. Requires 'Cave' and 'Wildlife Booster' x2": "时间 ^ 0.2。需要“洞穴”和“野生动物助推器”x2",
    "Time ^ 0.25. Requires 'Pond' and 'Wildlife Booster' x2": "时间 ^ 0.25。需要“池塘”和“野生动物助推器”x2",
    "Unlock a Larger Wildlife Buyable": "解锁更大的可购买野生动物",
    "Unlock Research": "解锁研究",
    "wildlife": "野生动物",
    "Wildlife ^ 0.3": "野生动物^ 0.3",
    "Wildlife gain increased based on Gardens": "野生动物增益根据花园而增加",
    "Wildlife gain x5": "野生动物增益 x5",
    "Wildlife multiplies its own gain": "野生动物成倍增加自己的收益",
    "Wildlife Time Affects Research": "野生动物时间影响研究",
    "Wildlife Time is 5x as Fast": "野生动物时间快 5 倍",
    "Wildlife Time x2 and Lose 20% as much Wildlife": "野生动物时间 x2 并损失 20% 的野生动物",
    "Wood Ant": "木蚁",
    "Woodlice": "木虱",
    "You gain twice as much Larger Wildlife": "您获得两倍的大型野生动物",
    "You lose half as much of your Wildlife every second": "你每秒失去一半的野生动物",
    "(sin (floor (time played / 2)) + 2) ^ 2": "(sin (floor (游戏时长 / 2)) + 2) ^ 2",
    "Arch": "拱门",
    "Educational Features": "教育特色",
    "Every 2π Seconds, Divide Garden Costs by 3, Changes Smoothly": "每2π秒，花园成本除以3，变化平稳",
    "Every 3π Seconds, Multiply Leaf Gain by 9, Changes Smoothly": "每3π秒，叶增益乘9，变化平滑",
    "Every π Seconds, Divide Garden Costs by 3, Changes Smoothly": "每π秒，花园成本除以3，变化平稳",
    "log10 -> log5": "日志10->日志5",
    "Multiply Research Speed and Point gain by Research. (free) Hold to buy max.": "将研究速度和研究点增益相乘。（免费）持有最多可购买。",
    "Outhouse": "外屋",
    "Pergola": "凉棚",
    "sin (floor (time played / 2)) + 2": "sin（floor（游戏时长/2））+ 2",
    "sin (time played) + 2": "sin（游戏时长）+ 2",
    "Tipi": "尖顶帐篷",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "MeT": "MeT",
    "YuC'e": "YuC'e",
    "Re": "Re",
    "QiV": "QiV",
    "SUS": "SUS",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'v8': 'v8',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Multiply Point gain by plants. Currently: ": "将点数增益乘以植物。目前：",
    "Tick Length: ": "Tick 长度: ",
    "Total Effect: ": "总效果：",
    "Your best zones is ": "你最佳的区域数量是 ",
    "Your best gardens is ": "你最佳的花园数量是 ",
    "Gardens + ": "花园 + ",
    "(log10(Points)) ^ ": "(log10(点数)) ^ ",
    "Plants ^ ": "植物 ^ ",
    "Points x (Plants ^ ": "点数 x (植物 ^ ",
    "log5(Points) ^ ": "log5(点数) ^ ",
    "Raise Plant cost dividers to ^ ": "将植物成本除以 ^",
    "Dev Speed: ": "开发速度：",
    "Reduce the Plant Cost base by ": "将植物成本基数降低 ",
    "Reduce Prickly Pear base by ": "减少刺梨基数 ",
    "Temp. Zone Completions + 1 ^ X. Currently Multiplying Point Gain when bought by x": "临时区域完成 + 1 ^ X。购买时当前点数增益乘以 x",
    "(Total Purchases ^ 0.5) ^ X. Currently Multiplying Point Gain when bought by x": "（总购买 ^ 0.5）^ X。购买时当前点数增益乘以 x",
    "Gardens ^ ": "花园 ^ ",
    "Gardens Reset Nothing and Divide Their Cost based on Zones | Currently: ": "花园不重置任何内容并除以它们的成本基于区域 | 当前：",
    "Zones + 1 ^ X. Currently Multiplying Point Gain when bought by x": "区域 + 1 ^ X。当购买时当前点数增益乘以 x",
    "Multiply Wildlife gain by ": "将野生动物增益乘以 ",
    "Multiplying Point gain by ": "将点增益乘以 ",
    "×/÷e": "×/÷e",
    "Fish ^ ": "鱼 ^ ",
    "Magnitude ^ ": "量级 ^ ",
    "Currently Multiplying Research and Point Gain when bought by ": "目前购买时研究和点数增益成倍增加 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " (Before Bonus Levels)": "（奖金等级之前）",
    " ^ Floor(log10(Plants))": " ^ Floor(log10(植物))",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\÷([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^\÷([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^×\/\÷([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\(([\d\.,]+) OOMs$/,
    /^\$([\d\.,]+)$/,
    /^\÷([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^×\/\÷([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^xe([\d\.,]+)$/,
    /^÷e([\d\.,]+)$/,
    /^e([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^×\/\÷([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) plants$/, '你有 $1 植物'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You Have (.+) Fish.$/, '你有 $1 鱼。'],
    [/^Points \^ N where N is X \÷ (.+). Currently: (.+)$/, '点数 \^ N where N is X \÷ $1. 当前: $2'],
    [/^(.+) \^ (.+) \= (.+), (.+) \= (.+) and (.+)$/, '$1 \^ $2 = $3, $4 = $5 和 $6'],
    [/^(.+)\/sec. You have (.+) Leaves, Dividing Tree Requirements by (.+).$/, '$1\/秒。您有 $2 树叶，将树需求除以 $3。'],
    [/^by (.+). Trees are Affected by the 1st Garden Milestone. You have (.+) Leaves, Dividing Tree Requirements by (.+).$/, '$1。树木受到第一个花园里程碑的影响。您有 $2 树叶，将树木需求除以 $3。'],
    [/^If you wrote (.+) digits per second, it would take you approximately (.+) seconds to write down your time spent researching.$/, '如果您每秒写 $1 位数字，则大约需要 $2 秒才能写下您花在研究上的时间。'],
    [/^Multiply Research Time Gain by (.+). Hold to buy max.$/, '将研究时间收益乘以 $1。按下购买最大。'],
    [/^Divide Research Requirement by (.+). Hold to buy max.$/, '将研究要求除以 $1。按下购买最大。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You are generating (.+) Wildlife every second. You keep Wildlife Upgrades on reset. You have (.+) Larger Wildlife which is Multiplying Point gain by (.+) and Wildlife gain by (.+).$/, '你每秒生成 $1 野生动物。你保持野生动物升级重置。你有 $2 更大的野生动物，即乘以点数 $3 和野生动物增益 $4。'],
    [/^(.+) Plants \-\> (.+) Plants$/, '1.5rt 植物 \-\> 1.1rt 植物'],
    [/^Find Researchers to help. Researchers Multiply Research Gain by Researchers \+ (.+). You have (.+) Researchers. Hold to buy max.$/, '寻找研究人员来帮助。研究人员将研究增益乘以研究人员 \+ $1。您有 $2 个研究人员。按下购买最大。'],
    [/^Reach (.+) plants to unlock \(You have (.+) plants\)$/, '达到 $1 株植物即可解锁（您有 $2 株植物）'],
    [/^You have made a total of (.+) gardens$/, '你总共建造了 $1 花园'],
    [/^You have made a total of (.+) zones$/, '你总共建造了 $1 区域'],
    [/^Next Magnitude increase at (.+) Points (.+)$/, '下一个量级增加 $1 点数 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^(.+) Plants. \((.+)\)$/, '$1 植物. \($2\)'],
    [/^([\d\.]+) sec$/, '$1 秒'],
    [/^([\d\.]+) hour$/, '$1 小时'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) Wildlife$/, '$1e$2 野生动物'],
    [/^([\d\.]+)e([\d\.,]+) Trees$/, '$1e$2 树'],
    [/^([\d\.]+)e([\d\.,]+) Research$/, '$1e$2 研究'],
    [/^([\d\.]+)e([\d\.,]+) Plants$/, '$1e$2 植物'],
    [/^([\d\.,]+) Useless Paperclips$/, '$1 无用的回形针'],
    [/^([\d\.,]+) Wildlife$/, '$1 野生动物'],
    [/^([\d\.,]+) Research$/, '$1 研究'],
    [/^([\d\.,]+) zones$/, '$1 区域'],
    [/^([\d\.,]+) Zone$/, '$1 区域'],
    [/^([\d\.,]+) Zones$/, '$1 区域'],
    [/^([\d\.,]+) Trees$/, '$1 树'],
    [/^([\d\.,]+) Plant$/, '$1 植物'],
    [/^([\d\.,]+) Plants$/, '$1 植物'],
    [/^([\d\.,]+) Gardens$/, '$1 花园'],
    [/^([\d\.,]+) gardens$/, '$1 花园'],
    [/^([\d\.,]+) Fish$/, '$1 鱼'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Ecosystems$/, '$1 生态系统'],
    [/^([\d\.,]+) Reclaimed Ecosystems$/, '$1 回收的生态系统'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Next: (.+) plants$/, '下一个：$1 植物'],
    [/^Next: (.+) points$/, '下一个：$1 点数'],
    [/^Cost: (.+) Time Speed Increases. Amount: (.+).$/, '成本：$1 时间速度提升。数量：$2。'],
    [/^Cost: (.+) Trees. Amount: (.+).$/, '成本：$1 树。数量：$2。'],
    [/^Cost: (.+) Research. Amount: (.+).$/, '成本：$1 研究。数量：$2。'],
    [/^Cost: (.+) Gardens. Amount: (.+).$/, '成本：$1 花园。数量：$2。'],
    [/^Cost: (.+) Larger Wildlife. Amount: (.+).$/, '成本：$1 更大的野生动物。数量：$2。'],
    [/^Cost: (.+) Wildlife Boosters. Amount: (.+).$/, '成本：$1 野生动物助推器。数量：$2。'],
    [/^Cost: (.+). Amount: (.+).$/, '成本：$1。数量：$2。'],
    [/^Cost: (.+) Research$/, '成本：$1 研究'],
    [/^Cost: (.+) gardens$/, '成本：$1 花园'],
    [/^Cost: (.+) plants$/, '成本：$1 植物'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Fish \(Only Purchasable once Bought in \'Coral Reef\'\)$/, '成本：$1 鱼（只能在“珊瑚礁”中购买一次）'],
    [/^Cost: (.+) Fish$/, '成本：$1 鱼'],
    [/^Cost: (.+) wildlife$/, '成本：$1 野生动物'],
    [/^Cost: (.+) trees$/, '成本：$1 树'],
    [/^Cost: (.+) zones$/, '成本：$1 地区'],
    [/^Req: (.+) points$/, '要求：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Currently: x(.+). Currently Multiplying by (.+) When Bought$/, '当前：x$1。当前购买时乘以 $2'],
    [/^Currently: (.+)\/sec.$/, '当前：$1\/秒。'],
    [/^Currently: x(.+).$/, '当前：x$1。'],
    [/^Currently: (.+)$/, '当前：$1'],
    [/^Req: (.+) \/ (.+) plants$/, '要求：$1 \/ $2 植物'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+) \/ (.+) plants$/, '$1 \/ $2 植物'],
    [/^(.+) \/ (.+) Seconds$/, '$1 \/ $2 秒'],
    [/^(.+) \/ (.+) points$/, '$1 \/ $2 点数'],

]);